[project]
name = "busybuddy"
version = "0.1.0"
description = "An AI agent that turns 'busy work' into 'buddy work' by helping reduce the friction as you code"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "smolagents[openai,toolkit]>=1.21.3",
]
